[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "pymysql>=1.1.1",
    "python-dotenv>=1.0.1",
    "resend>=2.5.1",
    "uvicorn>=0.34.0",
]
